import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Box, createTheme, Flex, MantineProvider } from "@mantine/core";
import { Header } from "../layout/header/page";
import { Sidebar } from "../layout/Sidebar/page";
import { ManagerBpmnProvider } from "./libs/contexts/manager-bpmn-context";
import { Notifications } from "@mantine/notifications";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const theme = createTheme({
  /** Put your mantine theme override here */
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* ...các tags khác */}
        {/* <link
          rel="stylesheet"
          href="https://unpkg.com/@bpmn-io/properties-panel/dist/assets/properties-panel.css"
        />
        <link
          rel="stylesheet"
          href="https://unpkg.com/@bpmn-io/properties-panel/dist/assets/element-templates.css"
        /> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider theme={theme}>
          <Notifications />
          <Flex direction="column">
            {/* Header */}
            <Header />

            {/* Sidebar + Main */}
            <Flex flex={1} className="">
              <Box w={250} style={{ borderRight: '1px solid var(--mantine-color-gray-3)' }}>
                <Sidebar />
              </Box>
              <Box flex={1} p="md" className="text-black">
                <ManagerBpmnProvider>
                  {children}
                </ManagerBpmnProvider>
              </Box>
            </Flex>
          </Flex>
        </MantineProvider>
      </body>
    </html>
  );
}
